export const WIDGET_EVENTS = {
  // View Mode Actions
  SHOW_CHAT_VIDEO: 'SHOW_CHAT_VIDEO',
  SHOW_VIDEO_ONLY: 'SHOW_VIDEO_ONLY',
  SHOW_AUDIO_ONLY: 'SHOW_AUDIO_ONLY',
  CYCLE_WIDGET_MODE: 'CYCLE_WIDGET_MODE',

  // Media Actions
  TOGGLE_VIDEO: 'TOGGLE_VIDEO',
  TOGGLE_AUDIO: 'TOGGLE_AUDIO',
  TOGGLE_CHAT: 'TOGGLE_CHAT',

  STATE_UPDATE: 'STATE_UPDATE',

  MEDIA_CONNECTING: 'MEDIA_CONNECTING',
  MEDIA_CONNECTED: 'MEDIA_CONNECTED',
  MEDIA_CONNECTION_FAILED: 'MEDIA_CONNECTION_FAILED',

  CHAT_CONNECTING: 'CHAT_CONNECTING',
  CHAT_CONNECTED: 'CHAT_CONNECTED',
  CHAT_CONNECTION_FAILED: 'CHAT_CONNECTION_FAILED',
  
  // Emoji Actions
  EMOJI_SELECTED: 'EMOJI_SELECTED',
  EMOJI_MODEL_OPENED: 'EMOJI_MODEL_OPENED',
  RESIZE_WIDGET: 'RESIZE_WIDGET',
} as const;


export const MEDIA_CONFIG_ACTIONS = {
  PLAYBACK_FAILED: 'PLAYBACK_FAILED',

};

export type WidgetActionType = typeof WIDGET_EVENTS[keyof typeof WIDGET_EVENTS];


